# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.20
# 
# >> macros
# << macros

Name:       mkdevnodes
Summary:    Fast MAKEDEV replacement
Version:    0.2
Release:    1
Group:      Applications/System
License:    GPLv2
Source0:    mkdevnodes-%{version}.tar.gz
Source100:  mkdevnodes.yaml


%description
A replacement for MAKEDEV. Instead of parsing hard-coded text files, mkdevnodes uses the information provided in sysfs to generate device nodes with mknod() as needed, as well as a few base device nodes that always need to be present. Mkdevnodes is thus extremely fast, as it doesn not need to read and/or parse text files from the root filesystem.




%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre


make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post






%files
%defattr(-,root,root,-)
/sbin/mkdevnodes
# >> files
# << files


